### PR TITLE
Added iteration count and data file params support.

### PR DESCRIPTION
**Pull request by vkbishnoi**

### CODE REVIEW

**Comment by vkbishnoi** [comment]
@AdmiringWorm / @agc93  / Team: Can someone please review my pull request. I have upgraded it to use latest Cake version as well 0.26.1.

**Comment by agc93** [comment]
@vkbishnoi This PR mostly looks good, but the build script fails as it hasn't been updated to reflect any of the changes.

If I get a chance, I will fix it and can merge then, but if you could update this, I could merge immediately.

**Comment by vkbishnoi** [comment]
@agc93 : Updated build.cake. My local build is green. Can you please review.

**Comment by agc93** [comment]
Thanks again @vkbishnoi !

I've just merged these changes and it's been published as [0.3.0-unstable0009 on NuGet](https://www.nuget.org/packages/Cake.Newman/0.3.0-unstable0009).

Can you test it out and make sure it works for you?

Thanks!

**Comment by agc93** [comment]
@vkbishnoi [Latest version](https://www.nuget.org/packages/Cake.Newman/0.3.0) is now stable on NuGet and includes all these changes and has been upgraded all the way 0.28.1.

Raise an issue if you see any problems with 0.3.x :+1:

**Pull request merged**
